### ISSUE TITLE
Pages are disappearing after refresh.

### ISSUE THREAD

**Issue by otabekoff** [wowthemesnet/mediumish-vuepress-blog-theme#5]
Pages are disappearing after refresh(F5, CTRL+R or whatever to refresh page).
Just redirecting to 404. I found the way on Netlify. But what about GitHub pages and on real web-servers? What should we do to fix that? Or is it a bug and you should fix it? Please let me know any changes about this.

Thank you very much.
Otabek Sadiridinov.

**Comment by OtabekSadiridinov** [comment]
Oh, don't mind it was my mistake with some routing. Now closing issue.

**Comment by KooXme** [comment]
Start

**Comment by KooXme** [comment]
> Pages are disappearing after refresh(F5, CTRL+R or whatever to refresh page).
> Just redirecting to 404. I found the way on Netlify. But what about GitHub pages and on real web-servers? What should we do to fix that? Or is it a bug and you should fix it? Please let me know any changes about this.
> 
> Thank you very much.
> Otabek Sadiridinov.
